apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: multus
  namespace: argocd
spec:
  destination:
    namespace: multus
    server: https://kubernetes.default.svc
  project: multus
  source:
    repoURL: https://k8s-at-home.com/charts/
    targetRevision: '3.5.2'
    chart: multus
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
